Стилизовал тудушки
tiltozavr/Casual-to-do-list pull request #7
Opened 2022-10-15 20:48 UTC by tiltozavr

2022-10-17 08:31 UTC, BartolomeoD commented on main.js
> +    if (choosenColor === "red") {
Лучше использовать switch

2022-10-17 08:42 UTC, BartolomeoD requested changes

2022-10-17 08:42 UTC, BartolomeoD commented on main.js
> +    let container = document.createElement("div");
Может тут тоже разложить на разные функции для кнопок

2022-10-17 08:42 UTC, BartolomeoD commented on main.js
> +function createMenuAdd(container) {
кажется что 4 функции очень похожи, можно сделать одну и то что разное просто вынести в параметры этой функции

2022-10-17 08:42 UTC, BartolomeoD commented on main.js
> +    buttonEl.style.backgroundImage = `url(${THREEDOTS_URL})`
style лучше перенести в css

2022-10-17 08:55 UTC, BartolomeoD commented
Еще файл main.js стал очень большим. Его стоит разделить на отдельные файлы

2022-10-17 18:34 UTC, tiltozavr commented on main.js
> +    buttonEl.style.backgroundImage = `url(${THREEDOTS_URL})`
@BartolomeoD 
Как при этом можно использовать константу?

2022-10-18 11:56 UTC, BartolomeoD approved these changes
NICE CHANGES BRO

2022-10-18 17:17 UTC, merged